
#include <stdio.h>
#include <iostream>
#include <sstream>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>

using namespace std;
using namespace cv;

Mat frame; //current frame
Mat fgMaskMOG; //fg mask generated by MOG method
Ptr<BackgroundSubtractor> pMOG; //MOG Background subtractor

int main(int argc, char** argv)
{
  VideoCapture cap(1); // Capture video form camera
  if(!cap.isOpened()) // if not success, exit program
  {
    cout << "cannot open camera" << endl;
  }

  //create window
  namedWindow("Frame");
  namedWindow("FG Mask MOG");
  
  //create Background Subtractor objects
  pMOG = new BackgroundSubtractorMOG(); //MOG approach
  
  while(1)
  {
    cap.read(frame);

    //update the background model
    pMOG->operator()(frame, fgMaskMOG);
    
    //show the current frame and the fg masks
    imshow("Frame", frame);
    imshow("FG Mask MOG", fgMaskMOG);
  
    if (waitKey(1) == 27) //wait for 'esc' key press for 1ms. If 'esc' key is pressed, break loop
    {
      cout << "esc key is pressed" << endl;
        break;
    }
  }
  return 0;
}