
#include <stdio.h>
#include <iostream>
#include <sstream>

#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/video/background_segm.hpp>

using namespace std;
using namespace cv;

Mat frame; //current frame
Mat fgMaskMOG; //fg mask generated by MOG method
Ptr<BackgroundSubtractor> pMOG; //MOG Background subtractor
Mat fgMaskMOG2; //fg mask generated by MOG2 method
Ptr<BackgroundSubtractor> pMOG2; //MOG2 Background subtractor

int main(int argc, char** argv)
{
   VideoCapture inputVideo("../doubleRecord/video1.avi");              // Open input
    if (!inputVideo.isOpened())
    {
        cout  << "Could not open the input video 1" << endl;
        return -1;
    }

  //create window
  namedWindow("Frame");
  namedWindow("FG Mask MOG2");
  namedWindow("FG Mask MOG1");
  
  //create Background Subtractor objects
  pMOG2 = new BackgroundSubtractorMOG2(); //MOG approach
  pMOG = new BackgroundSubtractorMOG(); //MOG approach
  
  while(1)
  {
    inputVideo.read(frame);

    //update the background model
    pMOG2->operator()(frame, fgMaskMOG2);
    pMOG->operator()(fgMaskMOG2, fgMaskMOG);
    
    //show the current frame and the fg masks
    imshow("Frame", frame);
    imshow("FG Mask MOG", fgMaskMOG);
    imshow("FG Mask MOG 2", fgMaskMOG2);
  
    if (waitKey(20) == 27) //wait for 'esc' key press for 1ms. If 'esc' key is pressed, break loop
    {
      cout << "esc key is pressed" << endl;
        break;
    }
  }
  return 0;
}
